AllowedHosts: "*"

Logging:
  LogLevel:
    Default: Warning

Test: 123

JwtAuthorize:
  Secret: ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890
  Issuer: gsw
  Audience: api
  PolicyName: permission
  DefaultScheme: Bearer
  IsHttps: false
  Expiration: 50000

datasource:
  driver-class-name: com.mysql.jdbc.Driver
  url: jdbc:mysql://127.0.0.1:3306/test
  username: root
  password: root